name: mots_tracker
channels:
  - conda-forge
  - defaults
  - open3d-admin
dependencies:
  - click
  - filterpy==1.4.5
  - ipython
  - lap==0.4.0
  - matplotlib==3.3.3
  - nb_conda
  - numpy>=1.13.3
  - opencv>=4.1.0.25
  - open3d==0.9.0
  - Pillow==8.0.1
  - pip
  - pycocotools==2.0.2
  - python>=3.6
  - scipy
  - pip:
     - -e .
     - bbox==0.9.2

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
