name: mots_tracker
channels:
  - conda-forge
  - open3d-admin
dependencies:
  - python=3.6
  - pip
  - open3d==0.9.0
  - filterpy  
  - lap
  - opencv
  - pycocotools
  - pip:
     - -e .
     - numba
     - scp
     - click

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
