output_path: "./data/output/3dbb_egomotion"
cores: 3

reader:
  type: NewMOTSynthReader
  args:
    data_path: "/home/vy/university/thesis/datasets/MOTSynth"
    ann_path: "/home/vy/university/thesis/datasets/MOTSynth_annotations/all"
    boxes_path: "gt/gt.txt"
    masks_path: "gt/gt_masks.txt"
    resize_shape: null
    depth_path: "gt_depth_new"
    egomotion_path: "egomotion"
    split_path: "debug_split/test.txt"

tracker:
  type: BBox3dTracker
  args:
    max_age: 15
    min_hits: 1
    dist_threshold: 0.001
    use_egomotion: true
    depth_deviation: 1
