output_path: "./data/output/reproj"
cores: 3

reader:
  type: NewMOTSynthReader
  args:
    data_path: "/home/vy/university/thesis/datasets/MOTSynth"
    gt_path: "/home/vy/university/thesis/datasets/MOTSynth_annotations/all"
    read_boxes: true
    read_masks: true
    resize_shape: null
    depth_path: "gt_depth_new"
    egomotion_path: "egomotion"
    split_path: "debug_split/test.txt"

tracker:
  type: MedianProjectionTracker
  args:
    max_age: 15
    min_hits: 1
    dist_threshold: 0.001
    dims: [1080, 1920]
